require('dotenv').config();
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const User = require('./src/models/User');
const Product = require('./src/models/Product');

const connectDB = async () => {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log('MongoDB connected for seeding');
};

const products = [
  // CLOTHING (12)
  {
    name: 'Royal Blue Formal Shirt',
    description: 'Premium cotton formal shirt, wrinkle-resistant with slim fit cut. Perfect for interviews and meetings.',
    category: 'Clothing',
    price: 1299,
    discountPrice: 999,
    barcode: '8901234567890',
    rfid: 'RFC001',
    stock: 50,
    image: 'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=400&auto=format&fit=crop',
    tags: ['formal', 'shirt', 'blue', 'cotton', 'office', 'interview', 'men'],
    brand: 'Arrow',
  },
  {
    name: 'Classic White Formal Shirt',
    description: 'Crisp white cotton shirt for formal occasions. Full-sleeve with French cuffs.',
    category: 'Clothing',
    price: 1199,
    discountPrice: 899,
    barcode: '8901234567891',
    rfid: 'RFC002',
    stock: 45,
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=400&auto=format&fit=crop',
    tags: ['formal', 'shirt', 'white', 'cotton', 'office', 'interview', 'men'],
    brand: 'Van Heusen',
  },
  {
    name: 'Navy Blue Slim Fit Trousers',
    description: 'Modern slim-fit formal trousers in navy blue. Comfortable stretch fabric.',
    category: 'Clothing',
    price: 1599,
    discountPrice: 1299,
    barcode: '8901234567892',
    rfid: 'RFC003',
    stock: 40,
    image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&auto=format&fit=crop',
    tags: ['formal', 'trousers', 'navy', 'office', 'interview', 'men', 'pants'],
    brand: 'Peter England',
  },
  {
    name: 'Black Slim Jeans',
    description: 'Stylish slim fit black jeans for casual and semi-formal wear.',
    category: 'Clothing',
    price: 1499,
    discountPrice: 1199,
    barcode: '8901234567893',
    rfid: 'RFC004',
    stock: 60,
    image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&auto=format&fit=crop',
    tags: ['casual', 'jeans', 'black', 'denim', 'men', 'party'],
    brand: 'Levis',
  },
  {
    name: 'Floral Summer Kurti',
    description: 'Light and breezy floral print kurti. Cotton fabric, ideal for summers.',
    category: 'Clothing',
    price: 849,
    discountPrice: 649,
    barcode: '8901234567894',
    rfid: 'RFC005',
    stock: 55,
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=400&auto=format&fit=crop',
    tags: ['ethnic', 'kurti', 'floral', 'summer', 'cotton', 'women', 'casual'],
    brand: 'Biba',
  },
  {
    name: 'Red Party Dress',
    description: 'Stunning red midi dress for parties and events. Bodycon fit with side slit.',
    category: 'Clothing',
    price: 2299,
    discountPrice: 1799,
    barcode: '8901234567895',
    rfid: 'RFC006',
    stock: 25,
    image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=400&auto=format&fit=crop',
    tags: ['party', 'dress', 'red', 'women', 'evening', 'formal'],
    brand: 'Zara',
  },
  {
    name: 'Grey Blazer',
    description: 'Premium grey blazer with structured shoulders. Single-breasted, two-button closure.',
    category: 'Clothing',
    price: 2999,
    discountPrice: 2399,
    barcode: '8901234567896',
    rfid: 'RFC007',
    stock: 20,
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400&auto=format&fit=crop',
    tags: ['formal', 'blazer', 'grey', 'interview', 'men', 'office', 'suit'],
    brand: 'Raymond',
  },
  {
    name: 'Cotton Casual T-Shirt White',
    description: 'Comfortable 100% cotton round-neck t-shirt. Everyday essential.',
    category: 'Clothing',
    price: 399,
    discountPrice: 299,
    barcode: '8901234567897',
    rfid: 'RFC008',
    stock: 100,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&auto=format&fit=crop',
    tags: ['casual', 't-shirt', 'white', 'cotton', 'men', 'basic'],
    brand: 'H&M',
  },
  {
    name: 'Black Graphic T-Shirt',
    description: 'Trendy graphic print t-shirt for casual hangouts. Soft cotton fabric.',
    category: 'Clothing',
    price: 599,
    discountPrice: 449,
    barcode: '8901234567898',
    rfid: 'RFC009',
    stock: 75,
    image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&auto=format&fit=crop',
    tags: ['casual', 't-shirt', 'black', 'graphic', 'men', 'streetwear', 'party'],
    brand: 'Bewakoof',
  },
  {
    name: 'Festive Anarkali Suit',
    description: 'Gorgeous anarkali with embroidery work. Ideal for weddings and festivals.',
    category: 'Clothing',
    price: 2499,
    barcode: '8901234567899',
    rfid: 'RFC010',
    stock: 30,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400&auto=format&fit=crop',
    tags: ['ethnic', 'anarkali', 'festival', 'wedding', 'women', 'embroidery'],
    brand: 'Libas',
  },
  {
    name: 'Denim Jacket Blue',
    description: 'Classic blue denim jacket. Layering essential for all seasons.',
    category: 'Clothing',
    price: 1899,
    discountPrice: 1499,
    barcode: '8901234567900',
    rfid: 'RFC011',
    stock: 35,
    image: 'https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=400&auto=format&fit=crop',
    tags: ['casual', 'jacket', 'denim', 'blue', 'men', 'women', 'streetwear', 'party'],
    brand: 'Pepe Jeans',
  },
  {
    name: 'Black Chinos',
    description: 'Smart-casual black chino pants. Versatile for office and outings.',
    category: 'Clothing',
    price: 1299,
    discountPrice: 999,
    barcode: '8901234567901',
    rfid: 'RFC012',
    stock: 50,
    image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=400&auto=format&fit=crop',
    tags: ['casual', 'chinos', 'black', 'men', 'smart-casual', 'interview'],
    brand: 'US Polo',
  },

  // ELECTRONICS (8)
  {
    name: 'Wireless Noise-Cancelling Earbuds',
    description: 'True wireless earbuds with active noise cancellation. 30-hour battery life.',
    category: 'Electronics',
    price: 2999,
    discountPrice: 2499,
    barcode: '8901234568001',
    rfid: 'RFE001',
    stock: 30,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&auto=format&fit=crop',
    tags: ['earbuds', 'wireless', 'noise-cancelling', 'audio', 'tech'],
    brand: 'boAt',
  },
  {
    name: 'USB-C Fast Charging Cable',
    description: '2m braided USB-C to USB-C cable. 65W fast charging support.',
    category: 'Electronics',
    price: 399,
    discountPrice: 299,
    barcode: '8901234568002',
    rfid: 'RFE002',
    stock: 150,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&auto=format&fit=crop',
    tags: ['cable', 'usb-c', 'charging', 'accessory', 'tech'],
    brand: 'Anker',
  },
  {
    name: '20000mAh Power Bank',
    description: 'Compact power bank with 20000mAh capacity. Dual USB-A and USB-C ports.',
    category: 'Electronics',
    price: 1599,
    discountPrice: 1299,
    barcode: '8901234568003',
    rfid: 'RFE003',
    stock: 40,
    image: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&auto=format&fit=crop',
    tags: ['powerbank', 'charger', 'portable', 'tech', 'travel'],
    brand: 'Mi',
  },
  {
    name: 'Phone Case iPhone 15',
    description: 'Military-grade drop protection case for iPhone 15. Transparent back.',
    category: 'Electronics',
    price: 499,
    discountPrice: 349,
    barcode: '8901234568004',
    rfid: 'RFE004',
    stock: 80,
    image: 'https://images.unsplash.com/photo-1556656793-08538906a9f8?w=400&auto=format&fit=crop',
    tags: ['phone case', 'iphone', 'protection', 'accessory', 'tech'],
    brand: 'Spigen',
  },
  {
    name: 'Bluetooth Portable Speaker',
    description: '360° sound portable speaker. Waterproof IPX7, 12-hour playtime.',
    category: 'Electronics',
    price: 1999,
    discountPrice: 1599,
    barcode: '8901234568005',
    rfid: 'RFE005',
    stock: 25,
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&auto=format&fit=crop',
    tags: ['speaker', 'bluetooth', 'portable', 'waterproof', 'audio', 'tech'],
    brand: 'JBL',
  },
  {
    name: 'Smart Watch Fitness Tracker',
    description: 'Fitness band with heart rate monitor, SpO2, sleep tracking. AMOLED display.',
    category: 'Electronics',
    price: 2499,
    discountPrice: 1999,
    barcode: '8901234568006',
    rfid: 'RFE006',
    stock: 20,
    image: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=400&auto=format&fit=crop',
    tags: ['smartwatch', 'fitness', 'tracker', 'wearable', 'tech', 'health'],
    brand: 'Mi Band',
  },
  {
    name: 'Screen Protector Tempered Glass',
    description: '9H hardness tempered glass protector. Anti-fingerprint coating, universal 6.5".',
    category: 'Electronics',
    price: 199,
    discountPrice: 149,
    barcode: '8901234568007',
    rfid: 'RFE007',
    stock: 200,
    image: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=400&auto=format&fit=crop',
    tags: ['screen protector', 'phone', 'accessory', 'tech', 'protection'],
    brand: 'Gorilla',
  },
  {
    name: 'Wired Earphones with Mic',
    description: 'Bass-heavy wired earphones with in-line microphone. 3.5mm jack.',
    category: 'Electronics',
    price: 299,
    discountPrice: 199,
    barcode: '8901234568008',
    rfid: 'RFE008',
    stock: 90,
    image: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=400&auto=format&fit=crop',
    tags: ['earphones', 'wired', 'audio', 'mic', 'budget', 'tech'],
    brand: 'Sony',
  },

  // GROCERY (6)
  {
    name: 'Lays Magic Masala Chips',
    description: 'India\'s favourite Magic Masala flavoured potato chips. 52g pack.',
    category: 'Grocery',
    price: 20,
    barcode: '8901234569001',
    rfid: 'RFG001',
    stock: 500,
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400&auto=format&fit=crop',
    tags: ['snacks', 'chips', 'masala', 'lays', 'junk food'],
    brand: 'Lays',
  },
  {
    name: 'Coca-Cola 500ml',
    description: 'Refreshing Coca-Cola carbonated beverage, 500ml bottle.',
    category: 'Grocery',
    price: 40,
    barcode: '8901234569002',
    rfid: 'RFG002',
    stock: 300,
    image: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400&auto=format&fit=crop',
    tags: ['beverage', 'cold drink', 'cola', 'refreshing'],
    brand: 'Coca-Cola',
  },
  {
    name: 'Cadbury Dairy Milk Chocolate',
    description: 'Classic milk chocolate bar. 40g pack.',
    category: 'Grocery',
    price: 50,
    barcode: '8901234569003',
    rfid: 'RFG003',
    stock: 400,
    image: 'https://images.unsplash.com/photo-1606312619070-d48b4c652a52?w=400&auto=format&fit=crop',
    tags: ['chocolate', 'sweet', 'cadbury', 'snack', 'dairy milk'],
    brand: 'Cadbury',
  },
  {
    name: 'Hand Sanitizer 500ml',
    description: 'WHO-formula alcohol-based hand sanitizer. Kills 99.9% germs.',
    category: 'Grocery',
    price: 150,
    discountPrice: 99,
    barcode: '8901234569004',
    rfid: 'RFG004',
    stock: 150,
    image: 'https://images.unsplash.com/photo-1584556812952-905ffd0c611a?w=400&auto=format&fit=crop',
    tags: ['hygiene', 'sanitizer', 'health', 'essentials'],
    brand: 'Dettol',
  },
  {
    name: 'Tropicana Orange Juice 1L',
    description: 'Fresh-squeezed style orange juice, no added sugar. 1 litre tetra pack.',
    category: 'Grocery',
    price: 120,
    barcode: '8901234569005',
    rfid: 'RFG005',
    stock: 200,
    image: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=400&auto=format&fit=crop',
    tags: ['juice', 'orange', 'beverage', 'healthy', 'tropicana'],
    brand: 'Tropicana',
  },
  {
    name: 'Maggi 2-Minute Noodles (Pack of 6)',
    description: 'Classic Masala Maggi noodles, pack of 6. Ready in 2 minutes.',
    category: 'Grocery',
    price: 90,
    barcode: '8901234569006',
    rfid: 'RFG006',
    stock: 350,
    image: 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?w=400&auto=format&fit=crop',
    tags: ['noodles', 'maggi', 'instant', 'food', 'quick meal'],
    brand: 'Maggi',
  },

  // FOOTWEAR (4)
  {
    name: 'White Casual Sneakers',
    description: 'Lightweight white canvas sneakers. Lace-up closure, versatile for all outfits.',
    category: 'Footwear',
    price: 1299,
    discountPrice: 999,
    barcode: '8901234570001',
    rfid: 'RFF001',
    stock: 45,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&auto=format&fit=crop',
    tags: ['sneakers', 'white', 'casual', 'canvas', 'men', 'women'],
    brand: 'Puma',
  },
  {
    name: 'Oxford Formal Shoes Black',
    description: 'Premium leather Oxford shoes. Ideal for formal occasions and interviews.',
    category: 'Footwear',
    price: 2499,
    discountPrice: 1999,
    barcode: '8901234570002',
    rfid: 'RFF002',
    stock: 30,
    image: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=400&auto=format&fit=crop',
    tags: ['formal', 'shoes', 'black', 'leather', 'oxford', 'interview', 'men', 'office'],
    brand: 'Red Tape',
  },
  {
    name: 'Flip Flops Beach Sandals',
    description: 'Comfortable rubber flip flops for beach and casual wear.',
    category: 'Footwear',
    price: 299,
    discountPrice: 199,
    barcode: '8901234570003',
    rfid: 'RFF003',
    stock: 120,
    image: 'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400&auto=format&fit=crop',
    tags: ['sandals', 'flip flops', 'casual', 'beach', 'summer', 'men', 'women'],
    brand: 'Paragon',
  },
  {
    name: 'Running Sports Shoes',
    description: 'Lightweight running shoes with cushioned sole. Breathable mesh upper.',
    category: 'Footwear',
    price: 1999,
    discountPrice: 1599,
    barcode: '8901234570004',
    rfid: 'RFF004',
    stock: 40,
    image: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&auto=format&fit=crop',
    tags: ['running', 'sports shoes', 'athletic', 'gym', 'men', 'fitness'],
    brand: 'Adidas',
  },

  // HOME & LIVING (3)
  {
    name: 'Decorative Throw Pillow - Teal Velvet',
    description: 'Soft velvet decorative pillow with invisible zipper. Plush insert included. Size: 45×45 cm. Perfect for sofa, bed, or reading nook.',
    category: 'Home',
    price: 599,
    discountPrice: 449,
    barcode: '8901234571001',
    rfid: 'RFH001',
    stock: 80,
    image: 'https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=400&auto=format&fit=crop',
    tags: ['pillow', 'cushion', 'home decor', 'velvet', 'teal', 'bedroom', 'living room', 'soft furnishing'],
    brand: 'Home Centre',
  },
  {
    name: 'Printed Cotton Cushion Cover Set (5 pcs)',
    description: 'Set of 5 cotton cushion covers with vibrant block-print patterns. Fits standard 40×40 cm inserts. Machine washable.',
    category: 'Home',
    price: 799,
    discountPrice: 549,
    barcode: '8901234571002',
    rfid: 'RFH002',
    stock: 60,
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&auto=format&fit=crop',
    tags: ['pillow cover', 'cushion cover', 'home decor', 'cotton', 'printed', 'living room', 'soft furnishing', 'set'],
    brand: 'Fabindia',
  },
  {
    name: 'Memory Foam Neck Pillow – Travel',
    description: 'Ergonomic travel neck pillow made with slow-rebound memory foam. Foldable, includes carry bag. Ideal for long journeys.',
    category: 'Home',
    price: 899,
    discountPrice: 699,
    barcode: '8901234571003',
    rfid: 'RFH003',
    stock: 45,
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=400&auto=format&fit=crop',
    tags: ['pillow', 'neck pillow', 'travel', 'memory foam', 'sleep', 'comfort', 'journey'],
    brand: 'Sleepyhead',
  },
  {
    name: 'Pillow Cover',
    description: 'ULHAAS SUPR MICRO PILLOW COVER | Size: 45cm x 67cm | Article: 494A09187 | Soft microfiber fabric, washable, ideal for standard pillows',
    category: 'Home',
    price: 49,
    barcode: '8904132948549',
    rfid: 'RFH004',
    stock: 200,
    image: 'https://images.unsplash.com/photo-1592789705501-f9ae4278a9c9?w=400&q=80',
    tags: ['pillow', 'cover', 'home', 'bedding', 'microfiber', 'ulinacs'],
    brand: 'Ulinacs',
  },
];

const seedDB = async () => {
  try {
    await connectDB();

    // Clear existing data
    await Product.deleteMany({});
    await User.deleteMany({});
    console.log('Cleared existing products and users');

    // Seed products
    await Product.insertMany(products);
    console.log(`Seeded ${products.length} products`);

    // Create admin user
    const adminUser = new User({
      name: 'FlashCart Admin',
      email: 'admin@flashcart.com',
      password: 'Admin@1234',
      role: 'admin',
    });
    await adminUser.save();
    console.log('Admin user created: admin@flashcart.com / Admin@1234');

    // Create demo user
    const demoUser = new User({
      name: 'Demo User',
      email: 'demo@flashcart.com',
      password: 'Demo@1234',
      role: 'user',
      budget: 5000,
      preferences: ['Clothing', 'Electronics'],
    });
    await demoUser.save();
    console.log('Demo user created: demo@flashcart.com / Demo@1234');

    console.log('\n✅ Database seeded successfully!');
    console.log('──────────────────────────────────────');
    console.log('Admin:  admin@flashcart.com / Admin@1234');
    console.log('Demo:   demo@flashcart.com / Demo@1234');
    console.log('──────────────────────────────────────');
    process.exit(0);
  } catch (err) {
    console.error('Seed error:', err);
    process.exit(1);
  }
};

seedDB();
